global class add Implements Schedulable{
     global void Execute(SchedulableContext SC){
          //doSynch();
     integer a=10;
     integer b=20;
     integer c=a+b;
   //  Account s=new Account(Name='Anil123');
   //  insert s;
     
     }
     }
     /*add j = new add();

/*String seconds = '0'; //Execute at Zero Seconds
String minutes = '10,20,30,40,50'; //Execute at every 10th minute of hour
String hours = '*'; // Execute Every Hour
String dayOfMonth = '*'; // Execute Every Day of the Month
String month = '3'; //Execute only in November(11)
String dayOfWeek = '?'; //Execute on all 7 days of the Week
String year = '2012'; //Execute only for year 2009

String sch = seconds +''+ minutes +''+ hours +''+ dayOfMonth +''+ month +''+ dayOfWeek +''+year;
String str = system.now().addMinutes(02).format('ss mm HH dd MM ? yyyy');
//System.schedule('JobName',str,j); 
 */